
set(CMAKE_SHARED_LIBRARY_PREFIX "")
set(CMAKE_SHARED_LIBRARY_SUFFIX ".wasm")
set(CMAKE_CXX_OUTPUT_EXTENSION ".ll")

set(CMAKE_SHARED_LIBRARY_SONAME_C_FLAG "")
set(CMAKE_POSITION_INDEPENDENT_CODE OFF CACHE BOOL "")

set(UNIX 1)

set(CMAKE_DL_LIBS)

